apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://gradle:jdk21
        name: gradle build
        kind: build
        shell: sh
        run: |
          ./gradlew build
          find .
      - uses: cloudbees-io/publish-test-results@v1
        name: collect tests
        with:
          test-type: JUNIT
          folder-name: "**/build/test-results/**/TEST-*.xml"
