apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: upstream-sync
on:
  schedule:
    - cron: 0 * * * *
    - cron: 5 * * * *
    - cron: 10 * * * *
    - cron: 15 * * * *
    - cron: 20 * * * *
    - cron: 25 * * * *
    - cron: 30 * * * *
    - cron: 35 * * * *
    - cron: 40 * * * *
    - cron: 45 * * * *
    - cron: 50 * * * *
    - cron: 55 * * * *
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  sync:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: cloudbees-io/configure-git-global-credentials@v1
        name: Git global credentials
      - uses: docker://alpine/git:v2.45.2
        name: Say hello
        shell: sh
        run: |
          echo "Running git commands"
          git remote -v
          # git remote add upstream git@github.com:kestra-io/kestra.git
          git fetch --all
          git pull upstream develop
          git status
