apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: upstream-sync
on:
  schedule:
    - cron: 0 * * * *
    - cron: 5 * * * *
    - cron: 10 * * * *
    - cron: 15 * * * *
    - cron: 20 * * * *
    - cron: 25 * * * *
    - cron: 30 * * * *
    - cron: 35 * * * *
    - cron: 40 * * * *
    - cron: 45 * * * *
    - cron: 50 * * * *
    - cron: 55 * * * *
  workflow_dispatch:
permissions:
  scm-token-own: write
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  sync:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
      - uses: cloudbees-io/configure-git-global-credentials@v1
        name: Git global credentials
        with:
          token: ${{ cloudbees.scm.token }}
      - uses: docker://alpine/git:v2.45.2
        name: Say hello
        shell: sh
        run: |
          set -x
          echo "Running git commands"
          git config --global user.email "swashburn@cloudbees.com"
          git config --global user.name "Spike Washburn (ci-bot)"
          git clone git@github.com:swashbuck1r/kestra.git
          cd kestra
          git remote -v
          git remote add upstream https://github.com/kestra-io/kestra.git
          git fetch --all
          git merge upstream/develop --no-edit
          git push origin develop --no-verify
